version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://server:3000
    networks:
      - farm-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb+srv://farmAdmin:StrongPassword@farm-claster.rtbms.mongodb.net/farmDb?retryWrites=true&w=majority&appName=farm-claster
    networks:
      - farm-network

networks:
  farm-network:
    driver: bridge
