export enum UprawyType {
  PSZENICA = "PSZENICA",
  ZIEMNIAK = "ZIEMNIAK",
  JECZMIEN = "JECZMIEN",
  KUKURYDZA = "KUKURYDZA",
  RYZ = "RYZ",
  SOJA = "SOJA",
  OWIES = "OWIES",
  ZYTNO = "ZYTNO",
  PROSO = "PROSO",
  BURAK = "BURAK",
}
